min_os_version: 1.3.8
name: Zerobyte
package: community.lazycat.app.zerobyte
version: 0.12.0
description: "为您的远程存储提供强大的备份自动化功能，轻松加密、压缩和保护您的数据"
homepage: https://github.com/nicotsx/zerobyte
author: nicotsx
application:
  subdomain: zerobyte
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://zerobyte:4096/

services:
  zerobyte:
    # ghcr.io/nicotsx/zerobyte:v0.12
    image: registry.lazycat.cloud/czyt/nicotsx/zerobyte:7e6b3949ed76475d
    container_name: zerobyte
    binds:
      - /lzcapp/var/sync_dir:/sync_dir
      - /lzcapp/var/backup:/var/lib/zerobyte
      - /lzcapp/var/rclone:/root/.config/rclone

locales:
  zh:
    name: "Zerobyte"
    description: "为您的远程存储提供强大的备份自动化功能，轻松加密、压缩和保护您的数据"
  en:
    name: "Zerobyte"
    description: "Powerful backup automation for your remote storage Encrypt, compress, and protect your data with ease"
